
// This file has been generated by the GUI designer. Do not modify.
namespace ClarionApp
{
	public partial class MindViewer
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label l1b;
		
		private global::Gtk.Label l1g;
		
		private global::Gtk.Label l1m;
		
		private global::Gtk.Label l1r;
		
		private global::Gtk.Label l1w;
		
		private global::Gtk.Label l1y;
		
		private global::Gtk.Label l2b;
		
		private global::Gtk.Label l2g;
		
		private global::Gtk.Label l2m;
		
		private global::Gtk.Label l2r;
		
		private global::Gtk.Label l2w;
		
		private global::Gtk.Label l2y;
		
		private global::Gtk.Label l3b;
		
		private global::Gtk.Label l3g;
		
		private global::Gtk.Label l3m;
		
		private global::Gtk.Label l3r;
		
		private global::Gtk.Label l3w;
		
		private global::Gtk.Label l3y;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label labelx;
		
		private global::Gtk.Entry lred;
		
		private global::Gtk.Entry lgreen;
		
		private global::Gtk.Entry lblue;
		
		private global::Gtk.Entry lyellow;
		
		private global::Gtk.Entry lwhite;
		
		private global::Gtk.Entry lmagenta;
		
		private global::Gtk.Entry lapples;
		
		private global::Gtk.Entry lnuts;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ClarionApp.MindViewer
			this.Name = "ClarionApp.MindViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("Creature Bag");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(5));
			// Container child ClarionApp.MindViewer.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(7)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(20));
			this.table1.ColumnSpacing = ((uint)(20));
			this.table1.BorderWidth = ((uint)(1));
			// Container child table1.Gtk.Table+TableChild
			this.l1b = new global::Gtk.Label ();
			this.l1b.Name = "l1b";
			this.l1b.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1b);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1b]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l1g = new global::Gtk.Label ();
			this.l1g.Name = "l1g";
			this.l1g.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1g);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1g]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l1m = new global::Gtk.Label ();
			this.l1m.Name = "l1m";
			this.l1m.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1m);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1m]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(5));
			w3.RightAttach = ((uint)(6));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l1r = new global::Gtk.Label ();
			this.l1r.Name = "l1r";
			this.l1r.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1r);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1r]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l1w = new global::Gtk.Label ();
			this.l1w.Name = "l1w";
			this.l1w.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1w);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1w]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(6));
			w5.RightAttach = ((uint)(7));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l1y = new global::Gtk.Label ();
			this.l1y.Name = "l1y";
			this.l1y.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l1y);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.l1y]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(4));
			w6.RightAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2b = new global::Gtk.Label ();
			this.l2b.Name = "l2b";
			this.l2b.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2b);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2b]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2g = new global::Gtk.Label ();
			this.l2g.Name = "l2g";
			this.l2g.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2g);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2g]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2m = new global::Gtk.Label ();
			this.l2m.Name = "l2m";
			this.l2m.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2m);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2m]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(5));
			w9.RightAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2r = new global::Gtk.Label ();
			this.l2r.Name = "l2r";
			this.l2r.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2r);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2r]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2w = new global::Gtk.Label ();
			this.l2w.Name = "l2w";
			this.l2w.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2w);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2w]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(6));
			w11.RightAttach = ((uint)(7));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l2y = new global::Gtk.Label ();
			this.l2y.Name = "l2y";
			this.l2y.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l2y);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.l2y]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(4));
			w12.RightAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3b = new global::Gtk.Label ();
			this.l3b.Name = "l3b";
			this.l3b.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3b);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3b]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3g = new global::Gtk.Label ();
			this.l3g.Name = "l3g";
			this.l3g.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3g);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3g]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3m = new global::Gtk.Label ();
			this.l3m.Name = "l3m";
			this.l3m.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3m);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3m]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(5));
			w15.RightAttach = ((uint)(6));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3r = new global::Gtk.Label ();
			this.l3r.Name = "l3r";
			this.l3r.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3r);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3r]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3w = new global::Gtk.Label ();
			this.l3w.Name = "l3w";
			this.l3w.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3w);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3w]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(6));
			w17.RightAttach = ((uint)(7));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.l3y = new global::Gtk.Label ();
			this.l3y.Name = "l3y";
			this.l3y.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.l3y);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.l3y]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.LeftAttach = ((uint)(4));
			w18.RightAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("G");
			this.table1.Add (this.label10);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("B");
			this.table1.Add (this.label11);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label11]));
			w20.LeftAttach = ((uint)(3));
			w20.RightAttach = ((uint)(4));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Y");
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label12]));
			w21.LeftAttach = ((uint)(4));
			w21.RightAttach = ((uint)(5));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("M");
			this.table1.Add (this.label13);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.label13]));
			w22.LeftAttach = ((uint)(5));
			w22.RightAttach = ((uint)(6));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("W");
			this.table1.Add (this.label14);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.label14]));
			w23.LeftAttach = ((uint)(6));
			w23.RightAttach = ((uint)(7));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Leaflet 2:");
			this.table1.Add (this.label15);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label15]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Leaflet 3:");
			this.table1.Add (this.label16);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.label16]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("R");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelx = new global::Gtk.Label ();
			this.labelx.Name = "labelx";
			this.labelx.LabelProp = global::Mono.Unix.Catalog.GetString ("Leaflet 1:");
			this.table1.Add (this.labelx);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelx]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed2.Add (this.table1);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.table1]));
			w28.X = 15;
			w28.Y = 262;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lred = new global::Gtk.Entry ();
			this.lred.CanFocus = true;
			this.lred.Name = "lred";
			this.lred.IsEditable = true;
			this.lred.InvisibleChar = '●';
			this.fixed2.Add (this.lred);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lred]));
			w29.X = 78;
			w29.Y = 19;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lgreen = new global::Gtk.Entry ();
			this.lgreen.CanFocus = true;
			this.lgreen.Name = "lgreen";
			this.lgreen.IsEditable = true;
			this.lgreen.InvisibleChar = '●';
			this.fixed2.Add (this.lgreen);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lgreen]));
			w30.X = 78;
			w30.Y = 46;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblue = new global::Gtk.Entry ();
			this.lblue.CanFocus = true;
			this.lblue.Name = "lblue";
			this.lblue.IsEditable = true;
			this.lblue.InvisibleChar = '●';
			this.fixed2.Add (this.lblue);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblue]));
			w31.X = 78;
			w31.Y = 73;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lyellow = new global::Gtk.Entry ();
			this.lyellow.CanFocus = true;
			this.lyellow.Name = "lyellow";
			this.lyellow.IsEditable = true;
			this.lyellow.InvisibleChar = '●';
			this.fixed2.Add (this.lyellow);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lyellow]));
			w32.X = 77;
			w32.Y = 100;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lwhite = new global::Gtk.Entry ();
			this.lwhite.CanFocus = true;
			this.lwhite.Name = "lwhite";
			this.lwhite.IsEditable = true;
			this.lwhite.InvisibleChar = '●';
			this.fixed2.Add (this.lwhite);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lwhite]));
			w33.X = 77;
			w33.Y = 128;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lmagenta = new global::Gtk.Entry ();
			this.lmagenta.CanFocus = true;
			this.lmagenta.Name = "lmagenta";
			this.lmagenta.IsEditable = true;
			this.lmagenta.InvisibleChar = '●';
			this.fixed2.Add (this.lmagenta);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lmagenta]));
			w34.X = 77;
			w34.Y = 157;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lapples = new global::Gtk.Entry ();
			this.lapples.CanFocus = true;
			this.lapples.Name = "lapples";
			this.lapples.IsEditable = true;
			this.lapples.InvisibleChar = '●';
			this.fixed2.Add (this.lapples);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lapples]));
			w35.X = 76;
			w35.Y = 184;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lnuts = new global::Gtk.Entry ();
			this.lnuts.CanFocus = true;
			this.lnuts.Name = "lnuts";
			this.lnuts.IsEditable = true;
			this.lnuts.InvisibleChar = '●';
			this.fixed2.Add (this.lnuts);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lnuts]));
			w36.X = 76;
			w36.Y = 212;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Red:");
			this.fixed2.Add (this.label4);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label4]));
			w37.X = 48;
			w37.Y = 20;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Green:");
			this.fixed2.Add (this.label5);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label5]));
			w38.X = 36;
			w38.Y = 48;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Blue:");
			this.fixed2.Add (this.label6);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label6]));
			w39.X = 45;
			w39.Y = 73;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Yellow:");
			this.fixed2.Add (this.label7);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label7]));
			w40.X = 35;
			w40.Y = 100;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("White:");
			this.fixed2.Add (this.label8);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label8]));
			w41.X = 35;
			w41.Y = 129;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Magenta:");
			this.fixed2.Add (this.label9);
			global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label9]));
			w42.X = 20;
			w42.Y = 158;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Apples:");
			this.fixed2.Add (this.label1);
			global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
			w43.X = 33;
			w43.Y = 185;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nuts:");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w44.X = 42;
			w44.Y = 213;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 280;
			this.DefaultHeight = 411;
			this.Show ();
		}
	}
}
