
// This file has been generated by the GUI designer. Do not modify.
namespace ClarionDEMO
{
	public partial class Mind
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ClarionDEMO.Mind
			this.Name = "ClarionDEMO.Mind";
			this.Title = global::Mono.Unix.Catalog.GetString ("Mind");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
